# Generated by Django 3.1.7 on 2021-02-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210224_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseStudent',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
