# Generated by Django 3.1.7 on 2021-02-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20210224_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='scoreCourse',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
