# Generated by Django 3.1.7 on 2021-02-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20210224_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='scoreCourse',
            field=models.IntegerField(null=True),
        ),
    ]
